/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed71d6fd-e131-41aa-a99a-eb9bfb61882c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QP6zerZDF",
    "aws_user_pools_web_client_id": "477bg4emlcmqsqdojoe5pushs7",
    "oauth": {}
};

export default awsmobile;
