export const APP = "app";

export const exampleRecipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 15,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 57,
    healthScore: 17,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 282.04,
    id: 633008,
    title: "Aubergine Parmesan",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "http://www.foodista.com/recipe/4J4JWCJ4/aubergine-parmesan",
    image: "https://spoonacular.com/recipeImages/633008-312x231.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          title: "Calories",
          amount: 475.47,
          unit: "kcal",
          percentOfDailyNeeds: 23.77,
        },
        {
          name: "Fat",
          title: "Fat",
          amount: 27.56,
          unit: "g",
          percentOfDailyNeeds: 42.4,
        },
        {
          name: "Saturated Fat",
          title: "Saturated Fat",
          amount: 16.19,
          unit: "g",
          percentOfDailyNeeds: 101.2,
        },
        {
          name: "Carbohydrates",
          title: "Carbohydrates",
          amount: 22.58,
          unit: "g",
          percentOfDailyNeeds: 7.53,
        },
        {
          name: "Net Carbohydrates",
          title: "Net Carbohydrates",
          amount: 17.1,
          unit: "g",
          percentOfDailyNeeds: 6.22,
        },
        {
          name: "Sugar",
          title: "Sugar",
          amount: 10.2,
          unit: "g",
          percentOfDailyNeeds: 11.34,
        },
        {
          name: "Cholesterol",
          title: "Cholesterol",
          amount: 119.71,
          unit: "mg",
          percentOfDailyNeeds: 39.9,
        },
      ],
      ingredients: [
        {
          id: 11209,
          name: "aubergine",
          amount: 0.25,
          unit: "large",
        },
        {
          id: 18079,
          name: "bread crumbs",
          amount: 1,
          unit: "servings",
        },
        {
          id: 11549,
          name: "canned tomato sauce",
          amount: 3.75,
          unit: "Oz",
        },
        {
          id: 1123,
          name: "egg",
          amount: 0.25,
          unit: "",
        },
        {
          id: 1026,
          name: "mozzarella cheese",
          amount: 2,
          unit: "ounces",
        },
        {
          id: 1033,
          name: "parmesan cheese",
          amount: 0.5,
          unit: "cups",
        },
      ],
      caloricBreakdown: {
        percentProtein: 29.67,
        percentFat: 51.56,
        percentCarbs: 18.77,
      },
      weightPerServing: {
        amount: 349,
        unit: "g",
      },
    },
    summary:
      'You can never have too many main course recipes, so give Aubergine Parmesan a try. This recipe serves 4 and costs $2.82 per serving. One serving contains <b>475 calories</b>, <b>36g of protein</b>, and <b>28g of fat</b>. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. 1 person has tried and liked this recipe. A mixture of parmesan cheese, mozzarella cheese, tomato sauce, and a handful of other ingredients are all it takes to make this recipe so delicious. All things considered, we decided this recipe <b>deserves a spoonacular score of 60%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/eggplant-aubergine-parmesan-103534">Eggplant (Aubergine) Parmesan</a>, <a href="https://spoonacular.com/recipes/eggplant-aubergine-parmesan-103835">Eggplant (Aubergine) Parmesan</a>, and <a href="https://spoonacular.com/recipes/eggplant-aubergine-parmesan-103514">Eggplant (Aubergine) Parmesan</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "Slice aubergine and dip in egg and then roll in bread crumbs. Brown all of aubergine. Put sauce in bottom of baking dish.",
            ingredients: [
              {
                id: 18079,
                name: "breadcrumbs",
                localizedName: "breadcrumbs",
                image: "breadcrumbs.jpg",
              },
              {
                id: 11209,
                name: "eggplant",
                localizedName: "eggplant",
                image: "eggplant.png",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
              {
                id: 0,
                name: "roll",
                localizedName: "roll",
                image: "dinner-yeast-rolls.jpg",
              },
              {
                id: 0,
                name: "dip",
                localizedName: "dip",
                image: "",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step:
              "Layer browned aubergine, then Mozzarella cheese and Parmesan cheese. Cover with sauce and do another layer.",
            ingredients: [
              {
                id: 1026,
                name: "mozzarella",
                localizedName: "mozzarella",
                image: "mozzarella.png",
              },
              {
                id: 1033,
                name: "parmesan",
                localizedName: "parmesan",
                image: "parmesan.jpg",
              },
              {
                id: 11209,
                name: "eggplant",
                localizedName: "eggplant",
                image: "eggplant.png",
              },
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Bake at 375 degrees.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
        ],
      },
    ],
    spoonacularSourceUrl: "https://spoonacular.com/aubergine-parmesan-633008",
    usedIngredientCount: 1,
    missedIngredientCount: 5,
    likes: 0,
    calories: {
      name: "Calories",
      title: "Calories",
      amount: 475.47,
      unit: "kcal",
      percentOfDailyNeeds: 23.77,
    },
    savedOn: "14 March 2021",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 17,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 94,
    spoonacularScore: 98,
    healthScore: 75,
    creditsText: "Pick Fresh Foods",
    license: "CC BY 3.0",
    sourceName: "Pick Fresh Foods",
    pricePerServing: 414.24,
    id: 715769,
    title: "Broccolini Quinoa Pilaf",
    readyInMinutes: 30,
    servings: 2,
    sourceUrl: "http://pickfreshfoods.com/broccolini-quinoa-pilaf/",
    image: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          title: "Calories",
          amount: 625.07,
          unit: "kcal",
          percentOfDailyNeeds: 31.25,
        },
        {
          name: "Fat",
          title: "Fat",
          amount: 30.69,
          unit: "g",
          percentOfDailyNeeds: 47.22,
        },
        {
          name: "Saturated Fat",
          title: "Saturated Fat",
          amount: 3.32,
          unit: "g",
          percentOfDailyNeeds: 20.76,
        },
        {
          name: "Carbohydrates",
          title: "Carbohydrates",
          amount: 71.66,
          unit: "g",
          percentOfDailyNeeds: 23.89,
        },
        {
          name: "Net Carbohydrates",
          title: "Net Carbohydrates",
          amount: 62.1,
          unit: "g",
          percentOfDailyNeeds: 22.58,
        },
        {
          name: "Sugar",
          title: "Sugar",
          amount: 6.45,
          unit: "g",
          percentOfDailyNeeds: 7.16,
        },
        {
          name: "Cholesterol",
          title: "Cholesterol",
          amount: 0,
          unit: "mg",
          percentOfDailyNeeds: 0,
        },
      ],
      ingredients: [
        {
          id: 98840,
          name: "broccolini",
          amount: 0.5,
          unit: "bunch",
        },
        {
          id: 11215,
          name: "garlic clove",
          amount: 0.5,
          unit: "",
        },
        {
          id: 4053,
          name: "olive oil",
          amount: 0.5,
          unit: "tbsp",
        },
        {
          id: 11282,
          name: "onion",
          amount: 0.25,
          unit: "cup",
        },
        {
          id: 20035,
          name: "quinoa",
          amount: 0.5,
          unit: "cup",
        },
        {
          id: 6615,
          name: "vegetable broth",
          amount: 1,
          unit: "cups",
        },
        {
          id: 12155,
          name: "walnuts",
          amount: 1,
          unit: "oz",
        },
      ],
      caloricBreakdown: {
        percentProtein: 12.36,
        percentFat: 43.01,
        percentCarbs: 44.63,
      },
      weightPerServing: {
        amount: 482,
        unit: "g",
      },
    },
    summary:
      'If you want to add more <b>Mediterranean</b> recipes to your recipe box, Broccolini Quinoa Pilaf might be a recipe you should try. One portion of this dish contains around <b>20g of protein</b>, <b>31g of fat</b>, and a total of <b>625 calories</b>. This recipe serves 2 and costs $4.14 per serving. A few people really liked this main course. 95 people have made this recipe and would make it again. Head to the store and pick up quinoa, garlic clove, olive oil, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. It is brought to you by Pick Fresh Foods. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/spring-broccolini-kale-quinoa-bowls-734866">Spring Broccolini & Kale Quinoa Bowls</a>, <a href="https://spoonacular.com/recipes/orange-sesame-salmon-with-quinoa-broccolini-839832">Orange-Sesame Salmon with Quinoa & Broccolini</a>, and <a href="https://spoonacular.com/recipes/black-pepper-goat-cheese-and-chard-quinoa-with-roasted-broccolini-625829">Black Pepper Goat Cheese and Chard Quinoa with Roasted Broccolini</a>.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step:
              "In a large pan with lid heat olive oil over medium high heat.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
          },
          {
            number: 2,
            step: "Add onions and cook for 1 minute.",
            ingredients: [
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
            length: {
              number: 1,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step:
              "Add garlic and cook until onions are translucent and garlic is fragrant.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step:
              "Add quinoa to pan, stir to combine. Slowly add in broth and bring to a boil.Cover and reduce heat to low, cook for 15 minutes.In the last 2-3 minutes of cooking add in broccolini on top of the quinoa (do not stir) and cover.Uncover and toss broccolini and quinoa together.Season to taste with salt and pepper.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 98840,
                name: "broccolini",
                localizedName: "broccolini",
                image: "broccolini.jpg",
              },
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 1006615,
                name: "broth",
                localizedName: "broth",
                image: "chicken-broth.png",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: {
              number: 18,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Add walnuts and serve hot.",
            ingredients: [
              {
                id: 12155,
                name: "walnuts",
                localizedName: "walnuts",
                image: "walnuts.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    spoonacularSourceUrl:
      "https://spoonacular.com/broccolini-quinoa-pilaf-715769",
    usedIngredientCount: 1,
    missedIngredientCount: 6,
    likes: 0,
    calories: {
      name: "Calories",
      title: "Calories",
      amount: 625.07,
      unit: "kcal",
      percentOfDailyNeeds: 31.25,
    },
    savedOn: "2 April 2021",
  },
];
